# Generated by Django 4.1.4 on 2023-01-05 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weibo',
            old_name='key',
            new_name='keyword',
        ),
    ]
