# Generated by Django 4.1.4 on 2023-01-10 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_key_weibo_keyword'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyseResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentiment', models.CharField(max_length=32)),
            ],
        ),
    ]
