# Generated by Django 4.1.4 on 2023-01-10 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_analyseresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyseresult',
            name='blogID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.weibo'),
            preserve_default=False,
        ),
    ]
