# Generated by Django 4.1.4 on 2023-01-10 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_analyseresult_blogid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analyseresult',
            old_name='blogID',
            new_name='blog',
        ),
    ]
