# Generated by Django 4.1.4 on 2023-01-10 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_blogid_analyseresult_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyseresult',
            name='sentiment',
            field=models.SmallIntegerField(),
        ),
    ]
