# Generated by Django 4.1.4 on 2023-01-10 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_analyseresult_sentiment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analyseresult',
            old_name='sentiment',
            new_name='score',
        ),
        migrations.AddField(
            model_name='analyseresult',
            name='analysis',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
    ]
