# Generated by Django 4.1.4 on 2023-01-10 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_sentiment_analyseresult_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyseresult',
            name='score',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
