# Generated by Django 4.1.4 on 2023-01-10 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_weibo_dz_alter_weibo_pl_alter_weibo_zf'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=64)),
                ('count', models.IntegerField()),
            ],
        ),
    ]
